### ISSUE TITLE
DonPachi automactically boots to bios after stage 5, instead of continue with second loop.

### ISSUE THREAD

**Issue by jetcodisc** [satiator/compatibility#21] opened 2021-05-11 10:36 UTC
**What game is it?**

Title: Donpachi

Region: JP

Serial: ST-14405G

**Where did you get the image?**

Redump

**What is the behaviour you observe?**

Upon completing stage 5 of the first loop and after seeing "FINAL MISSION" of the cutscene, suddenly boots to the saturn bios screen.
It should be continued with the second loop of the game with harder difficulty instead.
Game starts over from first loop when I press "Start Application" in the saturn bios screen.
_(Check out video attached at the bottom)_

**What is the behaviour you expect?**

   After seeing "FINAL MISSION" at the end of stage 5 cutscene, it should be continued with the second loop of the game with 
   harder difficulty instead.

**Firmware / Menu**
v157 / v66

**Hardware**
Model: MK-80219-07
Region: NTSC-J

https://user-images.githubusercontent.com/84015393/117803043-c2e4c100-b288-11eb-97aa-18b393e4bf36.mp4

**Comment by DanEremita** [comment] 2022-09-05 15:43
Same issue here. 
Tried some different images but all of it is getting this error.

**Comment by privateye** [comment] 2022-09-23 23:24
Unable to reproduce this issue with the Redump disc image in menu 67 and the latest test firmware (satiatormshvsf-0). I completed the first loop and beat the first stage in the second loop.

(And yes, I played DonPachi, not DoDonPachi.)

**Comment by lordviceroy** [comment] 2023-10-15 12:21
Multiple people have confirmed this as fixed on latest FW in #help on the Discord.

**Closed as completed** 2024-09-12 05:09 UTC
