### ISSUE TITLE
Black Fire (USA) does not load

### ISSUE THREAD

**Issue by nitro322** [satiator/compatibility#24] opened 2021-08-21 02:13 UTC
**What game is it?**

Title: Black Fire

Region: US

Serial: MK-81003

**Where did you get the image?**

Redump-verified (http://redump.org/disc/16825/)

**Provide SHA1 hashes of the image file(s)**

```
452ebf5130e88893d906b7424a2f5d3be15bc621  Black Fire (USA) (Track 1).bin
12cd8de92e17186faeba60bb774589a3811ff5f7  Black Fire (USA) (Track 2).bin
cc4669f1a78d2ed6f485f60e3f273aeccda82115  Black Fire (USA).cue
```

**What is the behaviour you observe?**

Game does not load.  After launching game from menu, Saturn boot and copyright screens are displayed as usually, then screen goes black and nothing else loads.  ABC+Start non-functional.  Resetting either stays or goes right back to black screen.

Issue observed with both official and rings menus.  Some brief discussion and confirmation by one other discord member here:
https://discord.com/channels/491170063869673482/684677416870084619/878170015990444072

**What is the behaviour you expect?**

I would expect the game to load and be playable.  It is, according to the compatibility spreadsheet:
https://docs.google.com/spreadsheets/d/1NsgnKeMwA-ATlyKZfL3R44d8E_O9sFlWdXSnltFkE_A/edit#gid=0

Based on that, I have to assume this issue was introduced in a firmware update since the original test.  I'm currently on firmware 1.56 and menu 66.

Unfortunately, I cannot compare to a disc.  My physical copy is scratched beyond repair (label side is damaged).

**Comment by lordviceroy** [comment] 2022-03-31 20:01
I was able to reproduce this as well using the Redump versions ("2S" and "3S" both exhibit the same issue).

Hashes follow for both versions:
```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA1            452EBF5130E88893D906B7424A2F5D3BE15BC621
SHA1            9CAACB5E8587EB638074C91666519B7EA9A529BF
SHA1            A250E77DC32A001C275785EA76216162FFB7A208
```

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA1            452EBF5130E88893D906B7424A2F5D3BE15BC621
SHA1            12CD8DE92E17186FAEBA60BB774589A3811FF5F7
SHA1            907B6E3971497E0428C570BBD8DCB426BFFC16C1
```

FW 157 MNU 66
1.01 System BIOS
400GB SanDisk Ultra SDXC Red+Grey
FAT32, 64KB Block Size
No cartridge in slot

**Comment by ferraca** [comment] 2022-08-31 22:43
Hi! It is working fine to me using the last beta version (same that fix MvsSF). If more info is required, I can check to provide. I booted the game using Rings menu.

**Comment by privateye** [comment] 2022-09-23 15:28
Unable to reproduce this issue in the Redump disc image (NTSC-U) with menu 67 and the latest test firmware (satiatormshvsf-0).

**Comment by abrasive** [comment] 2022-10-25 21:41
Fixed in fw 160

**Closed as completed by abrasive** 2022-10-25 21:41 UTC
Labels: fix-pending
