### ISSUE TITLE
AMOK (all regions) crashes to BIOS after "START GAME" loading screen

### ISSUE THREAD

**Issue by legodano** [satiator/compatibility#22] opened 2021-05-12 22:36 UTC
**What game is it?**

Title: AMOK

Region: All (US, JPN & PAL)

Serial: 81064 (USA), T-7637G (JPN), MK81064-50 (PAL)

**Where did you get the image?**

Redump for all 3

**Provide SHA1 hashes of the image file(s)**
Doing all 3 discs would take a century so here's just the USA one
```
bfc53f49c4cdc671a08e0c343310763dd4be25b0 Amok (USA) (Track 1).bin 
91aaa5a6885e3a17c86013424d28f56b34ec64b5 Amok (USA) (Track 2).bin 
5a4ae3f6646be60b16d7b83d7d75267732cf5b3b Amok (USA) (Track 3).bin 
75fa5424164318f2cd39c1d53bbd0d18079ea515 Amok (USA) (Track 4).bin
2b170e888e9ee9eda56f89c7bac464e88c1c65da Amok (USA) (Track 5).bin
3fef0d4224e146985d4510bf05484945154302b4 Amok (USA) (Track 6).bin 
82a044dff02da7b4a6bb659877835c178cf7a5d9 Amok (USA) (Track 7).bin 
857659ba474f09acc5b5c493cf922f60ee713710 Amok (USA) (Track 8).bin  
7d9da34eba7d947378464be7549a268e8b146335 Amok (USA).cue  
```

**What is the behaviour you observe?**

After booting the game and reaching the title screen, hitting "START GAME" will go to a loading screen. The game will sit here for about a minute and then gets kicked out to the BIOS/multiplayer with the message "Cartridge unsuitable for system" despite no cartridge being present in the system. This behaviour is identical across all 3 version of the game.

**What is the behaviour you expect?**

The game should go to its "INITIAL LANDING" cutscene after loading for a couple of seconds, as shown here https://youtu.be/UgQyznkvxk8?t=54
The game had previously been reported as working, so this is likely a regression related to firmware or menu.

FW 157 / Menu 66
SD card is Samsung EVO 128Gb, formatted FAT32
Model: HST-3220 (white model 2)
Region: NTSC-J

**Comment by DerekPascarella** [comment] 2022-03-22 16:32
Wanted to add that I'm experiencing this issue, as well.  However, I don't receive the "Cartridge unsuitable for system" message, but instead just get returned to the Satiator menu.

FW 158 / MENU 66 (Patched AR Cart)

**Comment by lordviceroy** [comment] 2022-03-31 19:29
Confirmed same issue for me with the USA version (Redump). I do not get the "Cartridge unsuitable" message though. Steps to repro:

- Load Amok (USA)
- Select "Start Game"
- "Loading..." screen appears
- Crashes back to Saturn system menu

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA1            BFC53F49C4CDC671A08E0C343310763DD4BE25B0
SHA1            91AAA5A6885E3A17C86013424D28F56B34EC64B5
SHA1            5A4AE3F6646BE60B16D7B83D7D75267732CF5B3B
SHA1            75FA5424164318F2CD39C1D53BBD0D18079EA515
SHA1            2B170E888E9EE9EDA56F89C7BAC464E88C1C65DA
SHA1            3FEF0D4224E146985D4510BF05484945154302B4
SHA1            82A044DFF02DA7B4A6BB659877835C178CF7A5D9
SHA1            857659BA474F09ACC5B5C493CF922F60EE713710
SHA1            7D9DA34EBA7D947378464BE7549A268E8B14633
```

Also reproduced this with the JP version. Hash follows:

```
Algorithm       Hash     Path
---------       ----     ----
SHA1            AC11E1D8A41D7EBDA05E122BB9C4E20D9F3CFCDA
SHA1            E9FBDF71C5A86CF5464F0B9E221F7AB254C4C2A1
SHA1            222CFC2132E63050B680B7B184E67F59DD989EA6
SHA1            7980D16868B881CC2A6F71738FB5660F9E51BA5B
SHA1            E76A724F005180D7C168BED826F906A3BB644A00
SHA1            FFEB986AF1760FF2B65154BDB1AF4A27A1761FEF
SHA1            643AB198B3D155B80D8DE58F7FC2AEBA12178517
SHA1            0CD3AD55C0A50A8297273E2A7786899599529033
SHA1            6A72C019D4450F9934A7817B7691E84379258536
```

FW 157 MNU 66
1.01 System BIOS
400GB SanDisk Ultra SDXC Red+Grey
FAT32, 64KB Block Size
No cartridge in slot

**Comment by ferraca** [comment] 2022-08-31 22:44
Hi! It is working fine to me using the last beta version (same that fix MvsSF). If more info is required, I can check to provide. I booted the game using Rings menu.

**Comment by privateye** [comment] 2022-09-23 15:28
Unable to reproduce this issue in the Redump disc image (NTSC-U) with menu 67 and the latest test firmware (satiatormshvsf-0).

**Comment by abrasive** [comment] 2022-10-25 21:40
Fixed in fw 160

**Closed as completed by abrasive** 2022-10-25 21:40 UTC
Labels: fix-pending
