### ISSUE TITLE
Marvel Super Heroes vs. Street Fighter issue with some Saturn boards

### ISSUE THREAD

**Issue by babalou-japon** [satiator/compatibility#34] opened 2022-11-06 13:55 UTC
# #**What game is it?**

Title: Marvel Super Heroes vs. Street Fighter

Region: JP

Serial: SLPS-01915

**Where did you get the image?**

Redump

Marvel Super Heroes vs. Street Fighter (Japan).cue : 6c97592bc6d556adc633dd6626f12607c943378b

**Satiator Firmware / Menu**
v160 / v67 (last firmware + last menu)

**What is the behaviour you observe?**

Satiator on Saturn HST-3220/HST-0014 (with a VA-2 board, according the serial number) : 
The game boots normally. On the title screen, when I press "START", the home page of the bios is displayed. As a consequence, it's not possible to play  this game.

Satiator on Saturn HST-3220/HST-0021 (with a VA-15 board, according the serial number) : 
The game boots normally. On the title screen, when I press "START", the games starts without any issue and there's no freeze or reboot. Everything is okay.

**What is the behaviour you expect?**

Start normally this games on a Saturn HST-3220/HST-0014.

Is there any compatibility issues between the Satiator and some Saturn boards ?

Best regards.

**Comment by TrekkiesUnite118** [comment] 2023-07-31 00:54
I have a US Model 1 Saturn with the VA2 board revision. I wasn't able to reproduce this. I also tested with 3 different Model 2 Saturns with revisions VA5, VA6, and VA8. All of them worked fine with the latest firmware. I was using the official 4MB Cart and tested with both Redump rips as well as my own personal rip from my own disc.

**Comment by abrasive** [comment] 2024-02-06 22:29
Closing as I can't reproduce this on any of my units either.

**Closed as completed by abrasive** 2024-02-06 22:29 UTC
