### ISSUE TITLE
Multi-disc games require power cycling and manually loading the next disc from the Satiator menu to resume gameplay

### ISSUE THREAD

**Issue by lordviceroy** [satiator/compatibility#12] opened 2021-01-19 00:14 UTC
----------
For anyone wondering whether or not Satiator supports multi-disc games: **Yes, Satiator supports multi-disc games.**

Multi-disc games work perfectly fine, you just can't begin playing the next disc without power cycling and manually loading the next disc in the Satiator menu. In practice, this isn't a problem since the multi-disc games either force a save before the next disc, or they save in the background without user intervention before you load the next disc.

**This should be considered a quality of life improvement, not a bug or a broken feature/compatibility problem**. If you have any questions around this, please join the Satiator Discord and ask in the #help channel about it.
----------

**What game is it?**
Multiple; see list below (provided by Dr. Emerald Nova in Discord)
https://discordapp.com/channels/491170063869673482/745769134377140355/800275122136154132

Title: 
```
3x3 Eyes - Kyuusei Koushu S (JP)
DeathMask (JP) 
Desire (JP) 
Devil Summoner - Soul Hackers (JP) 
Doukyuusei 2 (JP) 
Eberouge (JP) 
Gekka Mugentan Torico (1M) (JP) 
Gekka Mugentan Torico (2M) (JP) 
Haunted Casino (JP) 
Lunacy (US) 
Lunar 2 - Eternal Blue (JP)
```

Region: Multiple; refer to above list

Serial: Multiple; not included here

**Where did you get the image?**
N/A

**Provide SHA1 hashes of the image file(s)**
N/A

**What is the behaviour you observe?**
It is not possible to continue playing a game where a disc swap is "required" to continue gameplay unless you power cycle the system, and manually load the next disc from the Satiator menu.

In order to continue playing, you need to power cycle the console, enter the Satiator menu, load the next disc, then resume gameplay from your save file.

- Where in the game?
When a disc swap is "required" to continue gameplay.

- What triggers the behaviour?
The end of gameplay on the disc.

**What is the behaviour you expect?**
I should be able to "virtually" swap to the next disc and continue gameplay, without having to power cycle the system, enter the Satiator menu, manually loading the next disc, and then opening my save.

- Provide comparison to a real disc if possible
When prompted, you open the disc tray, swap the discs, close the tray, and continue gameplay.

**Comment by gamedevsam** [comment] 2021-08-18 03:41
This is a very important feature, the only game I would like to play is Panzer Dragon Saga which is a 4 CD game.

**Comment by lordviceroy** [comment] 2021-08-18 05:05
@gamedevsam, PDS plays just fine as it does not _require_ a disc swap to continue. PDS allows you to save between each disc. This issue is specific to games where a disc swap is _required_ to continue _and you are not_ allowed to save before proceeding.

**Comment by TrekkiesUnite118** [comment] 2021-08-26 04:43
I think this List needs re-examined for a few reasons. First three of the games are the same game:

- Gekka Mugentan Torico (1M) (JP) 
- Gekka Mugentan Torico (2M) (JP) 
- Lunacy (US) 

These are all the same game, and I'm pretty sure that game makes a save behind the scenes to allow for disc swapping as the game will take you to the CD Player screen when you open the disc drive door.

Next up is DeathMask which as been confirmed to take you to the CD Player when you open the disc door at the disc swap screen, meaning it has to save otherwise you wouldn't be able to continue.

Soul Hackers gives a message at the end telling you to swap discs and to restart the game from the CD Player screen and select LOAD GAME at the title screen of Disc 2, which again implies it saved something.

Lunar 2 gives you a screen asking if you want to save at the end of Disc 1 and gives a message saying it's saving data.

So I think this list really needs to be investigated because if they all actually do save then there's really no point in fussing over this feature as you can just reset your Saturn and load up the next disc from the Satiator menu.

Also for what it's worth, it was against Sega's standards for certifying a game to not save when swapping a disc. It's in their official documentation that it must be done. I'd imagine any game not doing that would have failed certification and been sent back to the developer and not published.

**Comment by lordviceroy** [comment] 2021-08-26 06:45
Thanks for that information!

Seems like this may not be needed if we can confirm that all of those games do in fact write a new save in the background that lets you continue on the next disc, i.e. without user interaction. I personally did not test any of this - I only filed on behalf of Nova, who was one of the main beta testers - and I don't have the time to test each one in the near future, so I'd defer to you or someone else to test, confirm, and update the ticket. Barring that, maybe implementing disc swap support is for the best so as to try and replicate the "intended" experience... but I would defer to Abrasive to make the call in either case.

Regarding the title duplication - I was aware of this (e.g. different dumps, different regions) but left them in there for the sake of completeness. :)

**Comment by privateye** [comment] 2021-08-26 17:44
I can verify that Lunacy/Torico automatically saves when you are prompted to swap discs, hence it is fully playable with Satiator.

I haven't played Death Mask but, based on the discourse surrounding the English translation project, that game acts the same way too.

**Comment by lordviceroy** [comment] 2021-12-09 05:57
Just wanted to drop some updates in here since it seems like there is still some confusion surrounding this ticket on various forums, etc.:

- **Games spanning multiple discs or games that prompt the user to swap discs work perfectly fine.** They are fully compatible with Satiator. PDS, Deep Fear, whatever - they work. _This issue is essentially a "quality of life" improvement, not a blocker to playing the games in question (which are mostly Japanese anyway)._
- For the games called out by this issue, the game prompts you to swap the disc, but you of course cannot do this without exiting back to the system menu, re-entering the Satiator menu, and then loading the image for the next disc. Thanks to investigation by the community, it was confirmed that these games save your current progress to backup RAM - in some cases, without user intervention or prompting - so you can just go through the process described previously to load the next disc, then load up your save and continue as expected.
- This request is on Abrasive's roadmap (per Abrasive himself in the Discord), along with fixing MSH vs SF. ;)

**Comment by ryfu123** [comment] 2023-07-26 09:06
Thank you for everything.
I have been enjoying my time at satiator for over 2 years.

If possible, I would like to see the multi-disk issue resolved.
In the following adventure game,
The save is done before moving to the second disc, but to play the second disc, you have to load the save data from the first disc and then swap discs. This is a software specification.

However, I am permanently unable to play the second disc because the power must be turned off in order to enter the disc selection menu.
I have no choice but to play with the physical disc.

title:
Rampo (1995)(Sega)(JP)

**Comment by privateye** [comment] 2023-07-29 13:13
Do you have a save file at the point of the disc swap? It would be interesting to test this with other ODEs too.

**Comment by ryfu123** [comment] 2023-07-30 13:43
Thanks for the reply.
Unfortunately I do not own any other ODEs so I cannot verify this.
I am attaching the save file at the time of the disk swap in the hope that it can be used for your research.
To play this I have to boot on the first disk, load the save file and then swap to the second disk.
This save file was copied from the cartridge RAM to the Satiator using the [Save File Copier].

From a Saturn fan in Japan^^

[RAMPODATA01.zip](https://github.com/satiator/compatibility/files/12209320/RAMPODATA01.zip)

**Comment by privateye** [comment] 2023-07-30 23:19
I confirm that it's currently impossible to progress from the first disc of Rampo to the second disc on Satiator. Rhea/Phoebe is fully compatible with Rampo as it features a disc swap button on the ODE itself, and I believe that MODE has similar functionality too.

Here is how disc swapping works with the save file provided by @ryfu123, assuming that the save is in the Saturn's internal memory and a backup memory cartridge is not inserted:
1. In the main menu of disc one, select the bottom option.
2. Select `RAMPODATA01` and this message will appear: [disc1.png](https://user-images.githubusercontent.com/69020283/257080162-6e4dabf0-e028-404c-8d15-46f75801a86e.png)
3. Press the disc lid button* and swap in disc two.
4. Once the game detects disc two, it will proceed to the next cutscene.

\* Doing this while playing a Saturn game usually kicks you to the multiplayer menu, but Rampo suppresses this behaviour and keeps the message on screen when the disc lid is opened.

Attempting to load the save file directly from disc two just gives this message: [disc2.png](https://user-images.githubusercontent.com/69020283/257080234-15d89b58-9695-4704-b3b3-0e9966d6a830.png)

Rampo and other multi-disc games that have similar behaviour will be compatible with Satiator once planned support for disc swapping is added: https://discord.com/channels/491170063869673482/745769134377140355/1128860862757752922

**Comment by ryfu123** [comment] 2023-07-31 00:58
Thank you for your confirmation.
As you said, in ODE products such as Rhea.
I confirmed on youtube that disk swapping would be possible without any problem.

But for me satiator is the best product.
I hope it will be supported in the future.

I am glad to share this issue with you.
Thank you for spending your valuable time to research.

**Comment by abrasive** [comment] 2023-08-04 08:08
Here is a beta build of firmware & menu with multi-disc support, please test it when you get a chance.

[satiator_menumulti-1.zip](https://github.com/satiator/compatibility/files/12258600/satiator_menumulti-1.zip)
[satiatormulti-sys-1.zip](https://github.com/satiator/compatibility/files/12258602/satiatormulti-sys-1.zip)

All of the files for a disc set have to be in the same folder, with no other disc images. The cue files (or isos if that's what you're using) have to have the same name, except for the last digit in the name, which is the disc number. The first disc number must be 1 and up to 9 discs are supported. For example, my `Rampo` folder looks like:

```
Rampo/
    Rampo (Japan) (Disc 1).cue
    Rampo (Japan) (Disc 1) (Track 1).bin
    Rampo (Japan) (Disc 1) (Track 2).bin
    Rampo (Japan) (Disc 2).cue
    Rampo (Japan) (Disc 2) (Track 1).bin
    Rampo (Japan) (Disc 2) (Track 2).bin
```
Note how the cue file names are exactly the same except for the number. The bin files are ignored. The filename case has to match for this build (but I will fix that to ignore it later).

Now when I select the `Rampo` folder, I get a `Select Disc` menu listing `Disc 1` and `Disc 2` instead of the full filenames. If you see the filenames instead of the select disc menu, it isn't detecting the folder as a multidisc set - check there are no other isos/cues and that the cue/iso filenames match exactly except for that 1 digit.

Once it's running, open and close the CD drive lid to select the next disc.

**Comment by landstalker01** [comment] 2024-03-04 11:10
I tested the firmware by upgrading from fw159 with Menu67 simply replacing the old files in the root of my SDCard.
After updating and switching the Saturn off and on again, the menu showed up (s.th. with fw version github160-4 and Menu github-04).

I tried to load images from my SDCard (i did not change anything on the Card besides from FW and Menu), but only got a black screen after parsing the image. Not even the Sega-Logo showed up. I switched the console off and on again and tried another image -> same behaviour.

I put fw160 and Menu67 in the root of my SD (replaced the beta fw and Menu), updated, powercycled, the tested images were booting fine again.

Im using a Saturn (Multi Region, set US60) and an Action Replay 4MB card flashed provided on satiator.net (https://wiki.satiator.net/action_replay_patching).

So I couldn't test the disc swap functionality as the images I tried were not booting at all.
I got every game in its own folder. I did not rename any image for testing.
Is there something I did not take into account?

**Comment by privateye** [comment] 2024-03-04 15:40
@landstalker01 : Black screen bug was fixed in this firmware released on the Satiator Discord server - [satiatormulti-sys-2.zip](https://github.com/satiator/compatibility/files/14483831/satiatormulti-sys-2.zip)

**Comment by landstalker01** [comment] 2024-03-04 16:03
@privateye: Thank you for the link and the advise with the Discord channel.

In Discord there is also a satiatormulti-sys-3.zip (released one day after v2):
https://discord.com/channels/491170063869673482/745769134377140355/1137746289057091695

It states that even in Version 3 "all games are broken in satiator mode". 
I could not find any newer version than v3.

**Comment by privateye** [comment] 2024-03-04 16:08
@landstalker01 : `satiatormulti-sys-3` is broken, hence why I linked the previous version which works fine.

**Comment by landstalker01** [comment] 2024-03-05 12:09
@privateye: Thank you very much for the info.

I tested the firmware you posted (v2) and it is indeed working fine :D. I'm using it with the beta menu published alongside beta1 (satiator_menumulti-1.zip).


I ran into some other unexpected behavior not caused by the satiator which I want to share here in case s.o. experiences s.th. similar:
After flashing the new firmware, I could not load images from a region different from the Saturn's region. I flashed the old firmware back and the problem persisted.
After that, I was also (sometimes) getting black screens after booting images and (sometimes) my Saturn even stuck at the Sega-logo before loading the Satiator menu after a Power On or reset.
As for as I tested, these problems were caused by the Action Replay 4MB cartridge (which I flashed with the Firmware provided at satiator.net as mentioned above) not getting proper contact in the cartridge slot. For now, I solved it by putting a piece of paper behind the cartridge to align it properly within the cartridge slot.
As I did not mentioned those problems before (maybe, because I did not move my Saturn for a while) it was really hard for me to find the root cause so I hope this description will be helpfull to other persons.

**Comment by abrasive** [comment] 2024-09-11 10:00
This is resolved in firmware 161 / menu 68 which are now [linked from the wiki](https://wiki.satiator.net/).

The new firmware allows you to cycle between multiple disc images by opening and closing the CD drive lid. See [the instructions on the wiki](https://wiki.satiator.net/menu#multi-disc_mode) for further details on setting it up - it's usually just a matter of throwing all the files for one game into a dedicated folder.

**Closed as completed by abrasive** 2024-09-11 10:00 UTC
